### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by nanier** [JJack27/activate-power-mode#2]

**Comment by JJack27** [comment]
Hi, this is a plug-in package for atom ide. The url for downloading is:https://atom.io/
After you install this ide. Unzip this package in the following location: C:\Users\yourName.atom\packages

Then, use alt+ctrl+O to activate this mode. note that you should press alt+ctrl+R to reload the window every time you use it.

Have fun!

**Comment by nanier** [comment]
Thanks a lot!  Because I do not use the atom IDE, so this plug-in package is not for me . But Thanks for your detailed answer all the same!
