### ISSUE TITLE
Remove desktop shaking effect?

### ISSUE THREAD

**Issue by TrangDinhVan** [JJack27/activate-power-mode#4]
I love the effect of exploding text however desktop shaking makes me crazy, is there any way to remove that effect.

**Comment by JJack27** [comment]
You can either download my code, which have already removed the shaking functionality, or download the original code and do the following to remove the shaking effect:

**Comment by JJack27** [comment]
Find the file named "activate-power-mode.coffee" in the lib folder. Then find the function called "shake". There is a variable called "intensity", change that to 0 in order to remove the effect. I'm not a professional .coffee developer. I think there is a better way to do that. Have fun!

**Comment by TrangDinhVan** [comment]
Work like a charm! Thanks.
